src/main/java/org/apache/maven/buildcache/CachingMojosExecutionStrategy.java
=> MNG-7129 fix for cleanup of partial state

src/main/java/org/apache/maven/buildcache/CacheControllerImpl.java, src/main/java/org/apache/maven/buildcache/checksum/MavenProjectInput.java, src/main/java/org/apache/maven/buildcache/xml/CacheConfig.java, src/main/java/org/apache/maven/buildcache/xml/CacheConfigImpl.java, src/site/markdown/how-to.md, src/site/markdown/parameters.md, src/site/markdown/performance.md, src/site/markdown/remote-cache.md, src/site/markdown/usage.md
=> [MBUILDCACHE-13] rename remote.cache.* properties to maven.build.cache.*

src/main/java/org/apache/maven/buildcache/RemoteCacheRepositoryNoOp.java, src/main/java/org/apache/maven/buildcache/RemoteCacheRepositoryProvider.java, src/main/java/org/apache/maven/buildcache/xml/CacheConfigImpl.java
=> [MBUILDCACHE-15] maven.build.cache.enabled parameter is broken - fix

.github/workflows/maven.yml, pom.xml, src/test/java/org/apache/maven/buildcache/its/junit/IntegrationTestExtension.java
=> Use maven 3.9 by default, make maven4 optional using profiles

src/main/java/org/apache/maven/buildcache/CacheControllerImpl.java, src/main/java/org/apache/maven/buildcache/RemoteCacheRepositoryImpl.java
@maximilian-novikov @maximilian-novikov-db could you have a look at this one ?
I don't really understand why the remote cache would have to be checked before the local one...
=> [MBUILDCACHE-20] Use local cache before remote cache by default

src/main/java/org/apache/maven/buildcache/checksum/MavenProjectInput.java, src/test/java/org/apache/maven/buildcache/its/Issue21Test.java, src/test/projects/mbuildcache-21/.mvn/maven-build-cache-config.xml, src/test/projects/mbuildcache-21/pom.xml
https://issues.apache.org/jira/browse/MBUILDCACHE-21
=> [MBUILDCACHE-21] Improve directory checks

Jenkinsfile
=> Disable jdk 8 on jenkins

pom.xml, src/test/java/org/apache/maven/buildcache/its/BuildExtensionTest.java, src/test/java/org/apache/maven/buildcache/its/CoreExtensionTest.java, src/test/java/org/apache/maven/buildcache/its/RemoteCacheDavTest.java, src/test/java/org/apache/maven/buildcache/its/junit/BeforeEach.java, src/test/java/org/apache/maven/buildcache/its/junit/Inject.java, src/test/java/org/apache/maven/buildcache/its/junit/IntegrationTestExtension.java, src/test/projects/remote-cache-dav/.mvn/extensions.xml, src/test/projects/remote-cache-dav/.mvn/maven-build-cache-config.xml, src/test/projects/remote-cache-dav/pom.xml, src/test/projects/remote-cache-dav/src/main/java/org/example/Main.java, src/test/resources/logback.xml
=> Add a remote cache IT

src/site/markdown/cache.md
=> clean up the doc, as the project moved to ASF

src/site/markdown/getting-started.md, src/site/markdown/how-to.md, src/site/markdown/usage.md, src/site/resources/maven-build-cache-config.xml
Documentation updates - fixed references to config file after rename, added notes about subtree discovery aashitki A minute ago
[Individual Contributor License …
=> Documentation updates

.github/workflows/maven.yml, pom.xml, src/test/java/org/apache/maven/buildcache/its/junit/IntegrationTestExtension.java, src/test/projects/build-extension/pom.xml, src/test/projects/core-extension/.mvn/extensions.xml, src/test/projects/forked-executions-core-extension/.mvn/extensions.xml, src/test/projects/mbuildcache-21/pom.xml, src/test/projects/remote-cache-dav/.mvn/extensions.xml
=> [MBUILDCACHE-34] Improve IT test execution

pom.xml, src/main/java/org/apache/maven/buildcache/xml/CacheConfigImpl.java
=> [MBUILDCACHE-40] Upgrade to released maven 3.9.0

src/site/markdown/getting-started.md.vm
Adding `.vm` to the end of the file allows interpolating files.
=> Filter the project version into the getting started guide

src/main/java/org/apache/maven/buildcache/LocalCacheRepositoryImpl.java
=> add some log when saving file locally as nothing is displayed if this has been done or not

pom.xml
=> use junit bom

src/main/java/org/apache/maven/buildcache/CacheControllerImpl.java, src/test/java/org/apache/maven/buildcache/its/Issue56Test.java, src/test/java/org/apache/maven/buildcache/its/junit/IntegrationTestExtension.java, src/test/projects/mbuildcache-56-mojo-parameter-as-method/.mvn/maven-build-cache-config.xml, src/test/projects/mbuildcache-56-mojo-parameter-as-method/pom.xml, src/test/projects/mbuildcache-56-mojo-parameter-as-method/src/main/java/org/apache/maven/buildcache/Test.java
=> [MBUILDCACHE-56] fix NPE when mojo does not a have field with same name as parameter

src/site/markdown/getting-started.md.vm
the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)
you have to acknowledge this by using the following check-box.
[core-its]: …
=> [MBUILDCACHE-51] - Broken link to maven-build-cache-config.xml template on Getting Started page

src/test/java/org/apache/maven/buildcache/its/RemoteCacheDavTest.java
Clear log junk from passing tests so it's easier to find real problems.
=> remove debugging code

src/main/java/org/apache/maven/buildcache/RemoteCacheRepositoryImpl.java, src/test/java/org/apache/maven/buildcache/its/RemoteCacheDavTest.java
Part of the cache is to discover remote caches by sending GET http requests. These requests are exploratory probes in nature and assume 404 Not Found errors by design. Such errors should not be printed in logs with exceptions, because that makes logs look like there are errors
If …
=> [MBUILDCACHE-32] Do not print exception when probing builds

src/site/markdown/how-to.md
pulling in other changes.~~
commit message.~~
the …
=> Fix How To XSD links

.github/workflows/maven-verify-3.9.x.yml, .github/workflows/maven-verify.yml, pom.xml
=> Upgrade Maven core versions used in for GHA and in pom

src/site/markdown/index.md
Mostly make language more direct and active, and omit needless words.
=> Copy edits

pom.xml
=> [MBUILDCACHE-75] Upgrade to parent 41

pom.xml
=> revert some non needed changes from https://github.com/apache/maven-build-cache-extension/pull/110

.github/workflows/maven-verify-3.9.x.yml, .github/workflows/maven-verify.yml, src/main/mdo/build-cache-config.mdo
=> Fix javadoc:jar generation and add it in the verify goals

src/main/java/org/apache/maven/buildcache/DefaultProjectInputCalculator.java, src/main/java/org/apache/maven/buildcache/checksum/MavenProjectInput.java, src/test/java/org/apache/maven/buildcache/its/CoreExtensionTest.java, src/test/projects/core-extension/pom.xml
=> [MBUILDCACHE-76] add project version as part of hash key

src/main/java/org/apache/maven/buildcache/checksum/MavenProjectInput.java, src/main/java/org/apache/maven/buildcache/xml/CacheConfig.java, src/main/java/org/apache/maven/buildcache/xml/CacheConfigImpl.java, src/main/mdo/build-cache-config.mdo, src/test/java/org/apache/maven/buildcache/its/Issue76Test.java, src/test/java/org/apache/maven/buildcache/xml/CacheConfigImplTest.java, src/test/projects/mbuildcache-76/.mvn/extensions.xml, src/test/projects/mbuildcache-76/.mvn/maven-build-cache-config.xml, src/test/projects/mbuildcache-76/pom.xml, src/test/projects/mbuildcache-76/src/main/java/org/apache/maven/buildcache/Test.java
Fixes https://issues.apache.org/jira/projects/MBUILDCACHE/issues/MBUILDCACHE-81
- Add new `calculateProjectVersionChecksum` attribute to project versioning cache configuration to enable/disable calculation of the project version checksum input. The default is false to maintain original behavior for cache portability between versions.
- Add/update unit and integration tests to cover possible use cases. 
is to use the JIRA …
=> [MBUILDCACHE-81] - Add an option to include project version as part of the cache hash key

src/main/java/org/apache/maven/buildcache/BuildCacheMojosExecutionStrategy.java, src/main/java/org/apache/maven/buildcache/CacheControllerImpl.java, src/test/java/org/apache/maven/buildcache/its/IncrementalRestoreTest.java, src/test/projects/mbuildcache-incremental/.mvn/maven-build-cache-config.xml, src/test/projects/mbuildcache-incremental/pom.xml, src/test/projects/mbuildcache-incremental/src/main/java/org/apache/maven/buildcache/Test.java
This PR fixes https://issues.apache.org/jira/browse/MBUILDCACHE-80: 
- Fix triggering full builds from scratch when there is an existing cache hit for incremental builds with a higher goal than the highest cached goal.
- Fix missing restore of cached artifacts into project's build directory using provided project build final name.
Following this checklist to help us incorporate your contribution quickly and easily:
commit …
=> [MBUILDCACHE-80] - Fix for incremental builds with a higher goal than the highest cached goal is rebuilding the full project from scratch

src/main/java/org/apache/maven/buildcache/BuildCacheMojosExecutionStrategy.java, src/main/java/org/apache/maven/buildcache/xml/CacheConfig.java, src/main/java/org/apache/maven/buildcache/xml/CacheConfigImpl.java, src/site/markdown/parameters.md, src/test/java/org/apache/maven/buildcache/its/BuildExtensionTest.java
=> [MBUILDCACHE-93] Command line configuration to skip saving in cache

pom.xml
=> remove wrong tag in pom and use last maven 3 version for ITs

src/site/markdown/performance.md
=> [MBUILDCACHE-100] - Fix exclusion example in docs

src/main/mdo/build-cache-config.mdo, src/site/markdown/getting-started.md.vm, src/site/markdown/performance.md
Fix typos and grammar errors. There are no functional changes. …
=> Fix documentation typos

pom.xml, src/site/markdown/how-to.md, src/site/resources/maven-build-cache-config.xml, src/test/projects/build-extension/.mvn/maven-build-cache-config.xml, src/test/projects/core-extension/.mvn/maven-build-cache-config.xml, src/test/projects/duplicate-goals/.mvn/maven-build-cache-config.xml, src/test/projects/forked-executions-core-extension-remote/.mvn/maven-build-cache-config.xml, src/test/projects/forked-executions-core-extension/.mvn/maven-build-cache-config.xml, src/test/projects/include-exclude/.mvn/maven-build-cache-config.xml, src/test/projects/mandatory-clean/.mvn/maven-build-cache-config.xml, src/test/projects/mbuildcache-21/.mvn/maven-build-cache-config.xml, src/test/projects/mbuildcache-56-mojo-parameter-as-method/.mvn/maven-build-cache-config.xml, src/test/projects/mbuildcache-67/.mvn/maven-build-cache-config.xml, src/test/projects/mbuildcache-74-clean-cache-any-artifact/.mvn/maven-build-cache-config.xml, src/test/projects/mbuildcache-76/.mvn/maven-build-cache-config.xml, src/test/projects/mbuildcache-87/.mvn/maven-build-cache-config.xml, src/test/projects/mbuildcache-incremental/.mvn/maven-build-cache-config.xml, src/test/projects/per-module-flags/.mvn/maven-build-cache-config.xml, src/test/projects/remote-cache-dav/.mvn/maven-build-cache-config.xml, src/test/resources/org/apache/maven/buildcache/xml/build-cache-build-instance.xml, src/test/resources/org/apache/maven/buildcache/xml/build-cache-config-instance.xml, src/test/resources/org/apache/maven/buildcache/xml/build-cache-diff-instance.xml, src/test/resources/org/apache/maven/buildcache/xml/build-cache-report-instance.xml
=> [MBUILDCACHE-111] Documentation uses build-cache-config 1.0.0 XML schema instead of 1.2.0 schema

.github/workflows/maven-verify-3.9.x.yml, .github/workflows/maven-verify.yml
=> build against 4.0.0-rc-3

src/main/java/org/apache/maven/buildcache/hash/CloseableBuffer.java
=> [MBUILDCACHE-113] java.security.AccessController in java.security has been deprecated and marked for removal

.asf.yaml, .github/ISSUE_TEMPLATE/BUG.yml, .github/ISSUE_TEMPLATE/FEATURE.yml, .github/ISSUE_TEMPLATE/config.yml, .github/pull_request_template.md, .github/workflows/pr-automation.yml, .github/workflows/stale.yml, README.md, pom.xml
=> Enable GH issues

src/main/mdo/build-cache-config.mdo
Following this checklist to help us incorporate your
Note that commits might be squashed by a maintainer on merge.
This may not always be possible but is a best-practice.
A more thorough check will be performed on your pull request automatically.
To make clear that you license your contribution under
the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)
you have to acknowledge this by using the following check-box.
=> Issue #238 Fix build cache location documentation

src/site/markdown/index.md.vm
Following this checklist to help us incorporate your
Note that commits might be squashed by a maintainer on merge.
This may not always be possible but is a best-practice.
A more thorough check will be performed on your pull request automatically.
To make clear that you license your contribution under
the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)
you have to acknowledge this by using the following check-box.
=> Issue #280 Make it clear the Cache extension need core 3.9.x
